initKKC({
  regions: [
    {code: 1, name:'Alabama',          abbr:'AL'},
    {code: 2, name:'Alaska',           abbr:'AK'},
    {code: 3, name:'Arizona',          abbr:'AZ'},
    {code: 4, name:'Arkansas',         abbr:'AR'},
    {code: 5, name:'California',       abbr:'CA'},
    {code: 6, name:'Colorado',         abbr:'CO'},
    {code: 7, name:'Connecticut',      abbr:'CT'},
    {code: 8, name:'Delaware',         abbr:'DE'},
    {code: 9, name:'Florida',          abbr:'FL'},
    {code:10, name:'Georgia',          abbr:'GA'},
    {code:11, name:'Hawaii',           abbr:'HI'},
    {code:12, name:'Idaho',            abbr:'ID'},
    {code:13, name:'Illinois',         abbr:'IL'},
    {code:14, name:'Indiana',          abbr:'IN'},
    {code:15, name:'Iowa',             abbr:'IA'},
    {code:16, name:'Kansas',           abbr:'KS'},
    {code:17, name:'Kentucky',         abbr:'KY'},
    {code:18, name:'Louisiana',        abbr:'LA'},
    {code:19, name:'Maine',            abbr:'ME'},
    {code:20, name:'Maryland',         abbr:'MD'},
    {code:21, name:'Massachusetts',    abbr:'MA'},
    {code:22, name:'Michigan',         abbr:'MI'},
    {code:23, name:'Minnesota',        abbr:'MN'},
    {code:24, name:'Mississippi',      abbr:'MS'},
    {code:25, name:'Missouri',         abbr:'MO'},
    {code:26, name:'Montana',          abbr:'MT'},
    {code:27, name:'Nebraska',         abbr:'NE'},
    {code:28, name:'Nevada',           abbr:'NV'},
    {code:29, name:'New Hampshire',    abbr:'NH'},
    {code:30, name:'New Jersey',       abbr:'NJ'},
    {code:31, name:'New Mexico',       abbr:'NM'},
    {code:32, name:'New York',         abbr:'NY'},
    {code:33, name:'North Carolina',   abbr:'NC'},
    {code:34, name:'North Dakota',     abbr:'ND'},
    {code:35, name:'Ohio',             abbr:'OH'},
    {code:36, name:'Oklahoma',         abbr:'OK'},
    {code:37, name:'Oregon',           abbr:'OR'},
    {code:38, name:'Pennsylvania',     abbr:'PA'},
    {code:39, name:'Rhode Island',     abbr:'RI'},
    {code:40, name:'South Carolina',   abbr:'SC'},
    {code:41, name:'South Dakota',     abbr:'SD'},
    {code:42, name:'Tennessee',        abbr:'TN'},
    {code:43, name:'Texas',            abbr:'TX'},
    {code:44, name:'Utah',             abbr:'UT'},
    {code:45, name:'Vermont',          abbr:'VT'},
    {code:46, name:'Virginia',         abbr:'VA'},
    {code:47, name:'Washington',       abbr:'WA'},
    {code:48, name:'West Virginia',    abbr:'WV'},
    {code:49, name:'Wisconsin',        abbr:'WI'},
    {code:50, name:'Wyoming',          abbr:'WY'},
  ],
  count: 50,
  storageKey: 'kkc-usa-state',
  shareName: 'USA map',
  clearPrompt: 'Clear all states?',
  formatName: (r) => `${r.name} (${r.abbr})`,
  formatLabel: (l) => `${l.label}<small>${l.points} points</small>`,
  legendLabel: (l) => l.label,
  fullVB: { x: 0, y: 0, w: 960, h: 600 },
  initVB: { x: 0, y: 0, w: 960, h: 600 },
});
